### ISSUE TITLE
Karmada docs directory tidy

### ISSUE THREAD

**Issue by Poor12** [karmada-io/website#116]
**What would you like to be added**:
Now Karmada's docs looks a little messy and it's unfriendly to users. We need to tidy the Karmada docs directory.

**Why is this needed**:
Tidy Karmada's docs directory. I recommend the below:
.
├── Core Concepts 
│   ├── Resource template, pp, cpp, op, cop
├── Key Features 
├── Get Started //A small example for new users.
├── Tutorials //Guide for users to learn how to use key feature step by step.
├── Installation 
├── User Guide //Mainly used to introduce Karmada and its ecological features.
├── Administrator Guide //For administrator, including upgrade, migration, operation and maintenance.
├── Developer Guide //For developer, including secondary development, debug, configuration based on Karmada.
├── Contributor Guide //For contributor, including how to contribute to Karmada community.
├── Case Study //end-user cases.
├── Troubleshooting
└── FAQ
└── Reference

Organize existing docs：https://github.com/Poor12/karmada/tree/master/website_docs

TODO-list
- [ ] `Core Concepts`  Replenish
- [ ] `Key Features`  Replenish
- [ ] `Get Started` Replenish
- [ ] `User Guide`  FederatedHPA Replenish
- [ ] `User Guide` 全局资源视图聚合API部分与统一认证鉴权需分离
- [ ] `User Guide` 全局资源视图补充统一运维（exec、log）部分
- [ ] `User Guide` 全局资源视图补充资源、事件全局搜索部分
- [ ] `User Guide` 角色关注分离统一认证鉴权需与聚合API部分分离
- [ ] `User Guide` 角色关注分离补充全局资源配额部分
- [ ] `User Guide` 角色关注分离补充可复用调度策略部分
- [ ] `Administrator Guide` 补充迁移部分（包含单集群迁移、从kubefed迁移）
- [ ] `Administrator Guide` 补充Karmadactl指导手册
- [ ] `Administrator Guide` 补充monitoring监控日志部分
- [ ] `Developer Guide` 补充如何调试karmada部分
- [ ] `Developer Guide` 补充对Karmada-scheduler做自定义配置部分
- [ ] `Reference` Replenish

**Comment by kevin-wangzefeng** [comment]
It's recommend developer guide and contributor guide splited in different sections.

**Comment by kevin-wangzefeng** [comment]
Add key features section to highlight major features provided by karmada.

**Comment by RainbowMango** [comment]
Good Job, looks good to me.

**Comment by RainbowMango** [comment]
I propose to add `Tutorials` for people to learn features step by step.

**Comment by kevin-wangzefeng** [comment]
> ├── Core Concepts //核心概念
> │ ├── Resource template, pp, cpp, op, cop
> ├── Key Features //核心功能
> ├── Get Started //快速上手的一个小例子
> ├── Installation //安装手册
> ├── User Guide //用户指南，用于介绍Karmada及其生态的功能
> ├── Administrator Guide //集群运维人员指南，用于如何迁移应用至Karmada，升级Karmada，运维Karmada
> ├── Developer Guide //开发者指南，用于指导如何调试Karmada、面向Karmada做二次开发、对Karmada某些功能进行自定义配置等
> ├── Contributor Guide //贡献者指南，用于指导新手如何给Karmada项目做贡献
> ├── Case Study //用户案例
> ├── Troubleshooting
> └── FAQ
> └── Reference

LGTM, thanks
