### ISSUE TITLE
fix hero area on tablet

### ISSUE THREAD

**Issue by Arhell** [karmada-io/website#15]
/assign
![Screenshot_1](https://user-images.githubusercontent.com/26163841/158032648-1b581231-b6e2-4698-987d-29c6d932e1c0.png)

**Comment by RainbowMango** [comment]
Thanks @Arhell . How can I see the `hero area`? (I don't familiar with front end technology)

**Comment by Arhell** [comment]
> Thanks @Arhell . How can I see the `hero area`? (I don't familiar with front end technology)

I will correct
