### ISSUE TITLE
website update

### ISSUE THREAD

**Issue by Arhell** [karmada-io/website#156]
**What would you like to be added**:
1. update css to scss
2. update dependencies version

**Why is this needed**:
1. more easy to work wish css
2.  update to new versions, I think there are fixed bugs

I will update the site dependencies  as updates come in.

About scss agree if I update? @RainbowMango

**Comment by RainbowMango** [comment]
I just re-opened #79, yes the dependencies should be updated.

I'm not sure about the benefits of the scss thing, I think we should keep consistent with docusaurus.
