### ISSUE TITLE
remove unnecessary dependencies 

### ISSUE THREAD

**Issue by Arhell** [karmada-io/website#168]
**What would you like to be added**:
https://github.com/karmada-io/website/blob/main/package.json#L24

official json https://github.com/facebook/docusaurus/blob/main/website/package.json

**Why is this needed**:
the original does not have these dependencies

@RainbowMango ?

**Comment by RainbowMango** [comment]
I don't why and when this module was involved, but sure, we need to remove it if it is not needed.
