### ISSUE TITLE
Can we make a  docker image ?  then everyone can be run project in docker

### ISSUE THREAD

**Issue by samzong** [karmada-io/website#181]
**What would you like to be added**:

**Why is this needed**:

To a large extent, this will ensure a simple and clean environment. For many newcomers, just clone the repo, complete the changes, and then use docker to make the project run quickly

**Comment by RainbowMango** [comment]
I'm not sure I understand you correctly. Is there any example?

**Comment by rgrupesh** [comment]
@SAMZONG Something like [this](https://github.com/internetarchive/openlibrary/tree/master/docker#readme)?

**Comment by SAMZONG** [comment]
#382
