### ISSUE TITLE
add dependabot.yml

### ISSUE THREAD

**Issue by Arhell** [karmada-io/website#186]
**Why is this needed**:
for update https://github.com/karmada-io/website/blob/main/package-lock.json dependencies

**Comment by RainbowMango** [comment]
What's the `dependabot.yml` thing? Any links?

If you mean [this](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot), the maintainer can see the alerts.

**Comment by Arhell** [comment]
> What's the `dependabot.yml` thing? Any links?
> 
> If you mean [this](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-supply-chain-security#what-is-dependabot), the maintainer can see the alerts.

yes, it will help update critical bugs in our dependencies
