### ISSUE TITLE
[en] Documents needs to be updated in release-1.5

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/website#271]
**What would you like to be added**:
This issue tracks the documents that need to be improved in release-1.5:
- [x] Upgrading instruction: https://karmada.io/docs/administrator/upgrading/ 
       At least we need to document how to upgrade between minor releases and patch releases.
- [x] https://karmada.io/docs/userguide/scheduling/resource-propagating/

**Comment by rgrupesh** [comment]
@RainbowMango For the first issue, do you mean general guidelines or the actual script to upgrade?

**Comment by RainbowMango** [comment]
I didn't follow these tasks for a while but seems they are all resolved.
/close
