### ISSUE TITLE
Redundant fieldSelector section in Override Policy document

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/website#291]
**Task description**:

We have a duplicate section in `Override Policy`'s introduction, you can help clean up

![image](https://user-images.githubusercontent.com/78244870/211973408-ce63e367-f322-4786-a9ca-7925cec627fa.png)

**Solution**:

Update the following file:

```
docs\userguide\scheduling\override-policy.md
i18n\zh\docusaurus-plugin-content-docs\current\userguide\scheduling\override-policy.md
versioned_docs\version-v1.4.0\userguide\scheduling\override-policy.md
i18n\zh\docusaurus-plugin-content-docs\version-v1.4.0\userguide\scheduling\override-policy.md
```

About how to contribute, you can refer to: https://karmada.io/zh/docs/contributor/contribute-docs/

**Who can join or take the task**:

The good first issue is intended for `first-time contributors` to get started on his/her contributor journey.

After a contributor has successfully completed 1-2 good first issue's,
they should be ready to move on to `help wanted` items, saving the remaining `good first issue` for other new contributors.

**How to join or take the task**:

Just reply on the issue with the message `/assign` in a separate line.

Then, the issue will be assigned to you.

**How to ask for help**:

If you need help or have questions, please feel free to ask on this issue.
The issue author or other members of the community will guide you through the contribution process.

**Comment by fengshunli** [comment]
see https://github.com/karmada-io/website/pull/292 @XiShanYongYe-Chang
