### ISSUE TITLE
Add a document to explain the usage of build-in functions of luavm to users

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/website#343]
**What would you like to be added**:

Add a document to explain the usage of build-in functions to users:

https://github.com/karmada-io/karmada/blob/7502b2507f3c4004d94e272f5e03e1dfde83d0e2/pkg/resourceinterpreter/customized/declarative/luavm/kube.go#L24-L30

As talked in https://github.com/karmada-io/karmada/pull/3339/files#r1154331582

**Why is this needed**:

Enable users to better understand and use this function.

**Comment by yike21** [comment]
May I take it? It's helpful for users to explain the usage of build-in functions.
/assign
