### ISSUE TITLE
Add Navbar items to the header

### ISSUE THREAD

**Issue by 0904-mansi** [karmada-io/website#35]
/assign

**Comment by Arhell** [comment]
Hello, thanks for the issue but the site will be updated soon
https://github.com/karmada-io/website/pull/31

**Comment by 0904-mansi** [comment]
> Hello, thanks for the issue but the site will be updated soon #31

 Actually I want to work on this issue that's why I raised it.

**Comment by RainbowMango** [comment]
/close 
in favor of #38
