### ISSUE TITLE
Doc for introduce to verify signed karmada artifacts

### ISSUE THREAD

**Issue by liangyuanpeng** [karmada-io/website#379]
**What would you like to be added**:

Related: https://github.com/karmada-io/karmada/issues/3435

/assign 

**Why is this needed**:

**Comment by RainbowMango** [comment]
@liangyuanpeng  I see @zishen just opened an issue https://github.com/karmada-io/website/issues/448.

I wonder are you still working on this?

**Comment by zishen** [comment]
ohoh, I'm sorry I didn't see it, but I'd like to do this. Can you take a look?
#449
