### ISSUE TITLE
Request: Documentation of Karmada components

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/website#411]
**What documentation would you like to be added**:

I'd like to have a document to explain how many components in Karmada and what each component does.
Just like [the document of Kubernetes Components](https://kubernetes.io/docs/concepts/overview/components/).

**Why do you think this document is needed**:

An overview document about the components would help people understand the architecture of Karmada quickly.

**Where do you think the new document should be placed**:

I think the document could be placed under /Documentation/Core Concepts/Components.
More precisely, the document should be placed in this code directory:
https://github.com/karmada-io/website/tree/main/docs/core-concepts/components.md

**Comment by chaosi-zju** [comment]
you can preview the document at here:  [karmada components](https://github.com/chaosi-zju/karmada-website/blob/dev/docs/core-concepts/components.md)

can you help me to confirm if there are any major issues in the document ? I will continue to improve on this basis.

**Comment by RainbowMango** [comment]
/assign @chaosi-zju 
in favor of #420
