### ISSUE TITLE
Dockerize the app

### ISSUE THREAD

**Issue by punithnayak** [karmada-io/website#430]
**What would you like to be added**:
I would like to propose the addition of containerization to our application using Docker. This involves creating a Dockerfile and a docker-compose.yml file to define the application's services, dependencies, and configurations within containers.

**Why is this needed**:
Containerizing the application is essential for several reasons:

Portability: Docker containers encapsulate the application and its dependencies, ensuring consistent behavior across different environments, such as development, testing, and production. This portability reduces the chances of issues related to environment differences.

Isolation: Containers provide a level of isolation between the application and the host system, reducing potential conflicts and making it easier to manage dependencies.

Scalability: Docker allows for easy scaling of the application by deploying multiple instances of the containers. This enables us to handle increased loads and traffic efficiently.

Reproducibility: With Docker, we can recreate the exact same environment in which the application runs, ensuring consistent behavior and easier debugging.

Versioning and Rollback: Docker images can be versioned, allowing us to roll back to previous versions quickly if issues arise.

Continuous Integration and Deployment (CI/CD): Containerization plays a crucial role in modern CI/CD pipelines, enabling seamless integration, testing, and deployment processes.

Easier Deployment: Docker simplifies the deployment process, as we can package the entire application stack into a single container and deploy it across different platforms.

**Comment by RainbowMango** [comment]
Hi @punithnayak If I understand correctly, you are asking the same thing as #181, right?

**Comment by punithnayak** [comment]
Yes sorry didn't see that I genuinely apologize for this

**Comment by RainbowMango** [comment]
No worries,
