### ISSUE TITLE
Update Ingress to the default dependencinterpreter support list

### ISSUE THREAD

**Issue by XiShanYongYe-Chang** [karmada-io/website#439]
**What would you like to be added**:

As https://github.com/karmada-io/karmada/pull/3885, we need to update the site: https://karmada.io/docs/next/userguide/globalview/customizing-resource-interpreter/#interpretdependency

**Why is this needed**:

/help

**Comment by Shreya111111** [comment]
@XiShanYongYe-Chang kindly assign this to me

**Comment by XiShanYongYe-Chang** [comment]
Thanks a lot
/assign @Shreya111111

**Comment by Shreya111111** [comment]
@XiShanYongYe-Chang  just to confirm i have to add ingress in https://github.com/karmada-io/website/blob/main/docs/userguide/globalview/customizing-resource-interpreter.md
 which is right here.
![karmada](https://github.com/karmada-io/website/assets/95047638/c8e32a31-d831-4da8-9901-50e3b7a5e216)

**Comment by XiShanYongYe-Chang** [comment]
Hi @Shreya111111, we need to add a new line in this module:
```
Ingress(networking/v1)
```
