### ISSUE TITLE
Index page blank area issue

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/website#44]
**What would you like to be added**:
I guess there are two options to fill the blank:
- 1. re-organize the description of `What is Karmada?` 
- 2. move the architecture images from `How it works` up

**Why is this needed**:
There is a large white space right after `What is Karmada?` 

![image](https://user-images.githubusercontent.com/8268873/167051668-2eac084b-0a90-43a0-9867-a418de65ec44.png)

**Comment by RainbowMango** [comment]
@Arhell @rgrupesh How do you think?

**Comment by rgrupesh** [comment]
@RainbowMango re-organizing the description would be better. What say @Arhell ?

**Comment by RainbowMango** [comment]
We don't have other good-looking diagrams for now.

**Comment by rgrupesh** [comment]
> We don't have other good-looking diagrams for now.

I see. We could consider this in the future.
