### ISSUE TITLE
Karmada tutorials documentation improvement. 

### ISSUE THREAD

**Issue by zhzhuang-zju** [karmada-io/website#485]
**What would you like to be added**:

**Why is this needed**:

Line 82 creates a resource named deployment-search through the command ```kubectl create -f```.
https://github.com/karmada-io/website/blob/6e6656b7bcf80f62532be64e841c9a833d2aacba/docs/tutorials/karmada-search.md#L63-L82

And then，update the resource through the command ```kubectl create -f``` again. This method will generate an error that the resource already exists. Use command ```kubectl apply -f``` or ```kubectl edit``` instead.
https://github.com/karmada-io/website/blob/6e6656b7bcf80f62532be64e841c9a833d2aacba/docs/tutorials/karmada-search.md#L180-L203

**Comment by RainbowMango** [comment]
Yes, you are right, I'd prefer to `kubectl apply -f`.

Would you like to send a PR to fix it?

We usually work on `current` docs, so we need to update the following files:
- en: https://github.com/karmada-io/website/blob/main/docs/tutorials/karmada-search.md
- zh: https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/current/tutorials/karmada-search.md

In addition, given this is kind of a bug, so we need to update the previous version of docs:
- release 1.7:
  * en: https://github.com/karmada-io/website/blob/main/versioned_docs/version-v1.7/tutorials/karmada-search.md
  * zh: https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/version-v1.7/tutorials/karmada-search.md
- release 1.6:
  * en: https://github.com/karmada-io/website/blob/main/versioned_docs/version-v1.6/tutorials/karmada-search.md
  * zh: https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/version-v1.6/tutorials/karmada-search.md
- release 1.5:
  * en: https://github.com/karmada-io/website/blob/main/versioned_docs/version-v1.5/tutorials/karmada-search.md
  * zh: https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/version-v1.5/tutorials/karmada-search.md
- release 1.4:
  * en: https://github.com/karmada-io/website/blob/main/versioned_docs/version-v1.4/tutorials/karmada-search.md
  * zh: https://github.com/karmada-io/website/blob/main/i18n/zh/docusaurus-plugin-content-docs/version-v1.4/tutorials/karmada-search.md

**Comment by zhzhuang-zju** [comment]
OK, I'm willing to fix it.

**Comment by RainbowMango** [comment]
Thanks, all right, let's assign this to you.
/assign @zhzhuang-zju 

No rush, take your time.

**Comment by RainbowMango** [comment]
Here is the GitHub Workflow: https://karmada.io/docs/contributor/github-workflow

Feel free to let me know if you need any help.
