### ISSUE TITLE
Add more spaces above `Why Karmada`

### ISSUE THREAD

**Issue by RainbowMango** [karmada-io/website#62]
**What would you like to be added**:
Add more spaces above `Why Karmada`.

![image](https://user-images.githubusercontent.com/8268873/170160134-5a152390-0fd8-4f8c-bf78-b5118ec4d2c1.png)

**Why is this needed**:

**Comment by anu491** [comment]
/assign
 
I suppose a line break would do !

**Comment by RainbowMango** [comment]
Hi @anu491 Are you still working on this?

**Comment by anu491** [comment]
I am a bit short on time (framing my cover letter for Karmada the LFX mentorship program) . I see @Arhell has done some work here . Okay after going through his work , I realize I would have done something very similar to what he has done. I'll unassign then !

/unassign
