### ISSUE TITLE
Nit: Typo in 'Karmada Concepts' image

### ISSUE THREAD

**Issue by waltforme** [karmada-io/website#635]
Current website [shows](https://karmada.io/docs/core-concepts/concepts)
![image](https://github.com/karmada-io/website/assets/8633434/9a93ed5d-d96e-41c9-9f65-3d083084091a)

where 'configmap' is spelt as 'comfigmap' in the topmost block.

**Comment by RainbowMango** [comment]
Thanks @waltforme for spotting this. 
We will fix it as soon as possible.
/assign

**Comment by waltforme** [comment]
Thanks for the prompt response! @RainbowMango
