### ISSUE TITLE
add "Why Karmada" block indent

### ISSUE THREAD

**Issue by Arhell** [karmada-io/website#64]
**What would you like to be added**:
add indent
**Why is this needed**:
more "air"
![Screenshot_1](https://user-images.githubusercontent.com/26163841/170391506-8dfb5eea-b276-446f-9493-6a630ab20ce2.png)
/assign

**Comment by RainbowMango** [comment]
I guess this is the same issue with #62 and seems [@anu491](https://github.com/anu491) is working on it.

**Comment by anu491** [comment]
Yeah this issue could be closed ! And if @Arhell wants he could work on #62 , as I am caught up with something today(framing my cover letter for the LFX mentorship program🙂)  . Thanks anyways for reporting the duplicate though 👍
