### ISSUE TITLE
Some Supporters not seen in dark theme

### ISSUE THREAD

**Issue by psankhe28** [karmada-io/website#71]
**I would like to add a background and enhance UI so that this problem is solved**:

![image](https://user-images.githubusercontent.com/84843461/171797985-cefcad5e-1276-451b-b90b-7ee17df5df3f.png)

**As we can see in above screenshot,some supporters are not seen so this problem can be solved.**:

**Comment by RainbowMango** [comment]
Thanks @psankhe28 for reporting this issue. Just let me know if you want to take it.

cc @Arhell
