### ISSUE TITLE
Unable to translate the content to Chinese

### ISSUE THREAD

**Issue by Apurv428** [karmada-io/website#73]
<img width="960" alt="image" src="https://user-images.githubusercontent.com/84929607/171814747-add90cff-a0b1-430e-90d5-2f8aacf8e33e.png">

**What would you like to be added**:
All the content of the site should be translated to Chinese after opting for Chinese translation.
**Why is this needed**:
Better readbility for the Chinese users.

**Comment by RainbowMango** [comment]
Yes, you are right. We can start it now.

**Comment by windsonsea** [comment]
Hope we can implement this feature soon.

@RainbowMango Could I ask you to give me an honor become a Karmada memer after your sponsorship at https://github.com/karmada-io/community/issues/3, thanks a lot.

**Comment by RainbowMango** [comment]
/close
We are working on it now.
