### ISSUE TITLE
fix karmada icon on dark theme

### ISSUE THREAD

**Issue by rgrupesh** [karmada-io/website#76]
**What would you like to be added**:
Fix icon
<details>
  <summary>Before</summary>

![Screenshot from 2022-06-04 19-04-27](https://user-images.githubusercontent.com/54068868/172001006-37422fce-28f1-4c31-80ac-f14921872a59.png)

</details>

<details>
  <summary>After</summary>

![Screenshot from 2022-06-04 19-04-38](https://user-images.githubusercontent.com/54068868/172001023-f2d2f4c2-b2ae-40ba-9c0c-030dea100650.png)
</details>

**Why is this needed**:
For coherent display

**Comment by Arhell** [comment]
able to close https://github.com/karmada-io/website/pull/80

**Comment by RainbowMango** [comment]
@Arhell 
You can add `Fixes #76` in #89 PR description.
Or, you can close it by robot command:
/close
