### ISSUE TITLE
fix karmada logo on dark theme 

### ISSUE THREAD

**Issue by Arhell** [karmada-io/website#77]
**Why is this needed**:
![Screenshot_1](https://user-images.githubusercontent.com/26163841/172042762-05a4d407-571a-4d34-937d-1db5fb2ae021.png)
/assign

**Comment by rgrupesh** [comment]
@Arhell The issue seems to be duplicated. Please refer to #76

**Comment by Arhell** [comment]
> @Arhell The issue seems to be duplicated. Please refer to #76

no

**Comment by RainbowMango** [comment]
@rgrupesh where is the RP, #76 is the issue without assignment.

**Comment by RainbowMango** [comment]
Sorry, ignore my comments. I think this is a PR. :(
