### ISSUE TITLE
remove @mui/material

### ISSUE THREAD

**Issue by Arhell** [karmada-io/website#84]
**What would you like to be added**:
use docusaurus styles

**Why is this needed**:
remove optional dependency

/assign

**Comment by RainbowMango** [comment]
Hi @Arhell I don't understand what's the problem you are going to fix, what do you mean `use docusaurus styles`?

**Comment by Arhell** [comment]
> Hi @Arhell I don't understand what's the problem you are going to fix, what do you mean `use docusaurus styles`?

For the 1st block, a whole npm package is used (mui), which weighs quite a lot + -, I removed it and used the styles that come by default.
